// src/lib/components/SeedPapers.svelte
<script>
	let { queryResult, search, seeds } = $props();

	let status = $state(seeds.map((s) => ({ Title: s['Title'], Url: s['Url'], Status: undefined })));

	$effect(() => {
		const results = queryResult;
		if (!('search-results' in results)) return;
		const query = results['search-results']['opensearch:Query']['@searchTerms'];

		(async () => {
			for (let i = 0; i < status.length; i++) {
				const paper = status[i];
				const checkQuery = `${query} AND TITLE("${paper['Title']}")`;
				const result = await search(checkQuery);
				const included = result['search-results']['opensearch:totalResults'] > 0 ? 1 : 0;
				status = status.map((s, idx) => (idx === i ? { ...s, Status: included } : s));
			}
		})();
	});

	function icon(title) {
		const paper = status.find((d) => d['Title'] === title);
		if (paper?.['Status'] === 1) return '✓';
		if (paper?.['Status'] === 0) return '✕';
		return '?';
	}

	function iconClass(title) {
		const paper = status.find((d) => d['Title'] === title);
		if (paper?.['Status'] === 1) return 'text-success-500';
		if (paper?.['Status'] === 0) return 'text-error-500';
		return 'text-warning-500';
	}

	const total = $derived(seeds.length);
	const checked = $derived(status.filter((d) => d['Status'] !== undefined).length);
	const excluded = $derived(status.filter((s) => s['Status'] === 0));
	const toCheck = $derived(status.filter((s) => s['Status'] === undefined));
	const included = $derived(status.filter((s) => s['Status'] === 1));

	function list(name, items) {
		return [...items].sort((a, b) => a['Title'].localeCompare(b['Title']));
	}
</script>

{#snippet paperList(name, items, showSpin)}
	{#if items.length > 0}
		<div class="seed-papers">
			<span class="label"
				>Seed papers {name} ({items.length}/{total})
				{#if showSpin && checked !== total}(checking...){/if}</span
			>
			{#each list(name, items) as e (e['Title'])}
				<a
					class="block"
					href={e['Url']}
					target="_blank"
					rel="noreferrer"
				><span class={iconClass(e['Title'])}>{icon(e['Title'])}</span> {e['Title']}</a>
			{/each}
		</div>
	{/if}
{/snippet}

{@render paperList('excluded', excluded, false)}
{@render paperList('to check', toCheck, true)}
{@render paperList('included', included, false)}

// client/src/SeedPapers.jsx
import { CheckCircleFilled, CloseCircleFilled, QuestionCircleFilled } from "@ant-design/icons";
import { Spin } from "antd";
import React from "react";
import './SeedPapers.css';

class SeedPapers extends React.Component {
    constructor(props) {
        super(props);
        this.getIcon = this.getIcon.bind(this);
        this.getList = this.getList.bind(this);
        const status = this.props.seeds.map(s => ({ Title: s["Title"], Url: s["Url"], Status: undefined }));
        this.state = { status: status };
    }

    async componentDidMount() {
        if ("search-results" in this.props.queryResult) {
            const query = this.props.queryResult["search-results"]["opensearch:Query"]["@searchTerms"];
            for (let i = 0; i < this.state.status.length; i++) {
                const paper = this.state.status[i];
                const checkQuery = `${query} AND TITLE("${paper["Title"]}")`;
                const result = await this.props.search(checkQuery),
                    statusNew = this.state.status;
                statusNew[i]["Status"] = result["search-results"]["opensearch:totalResults"] > 0 ? 1 : 0;
                this.setState({ status: statusNew });
            }
        }
    }

    getIcon(title) {
        const paper = this.state.status.filter(d => d["Title"] === title)[0];
        let icon;
        switch (paper["Status"]) {
            case 1:
                icon = <CheckCircleFilled style={{ color: "#52c41a" }} />;
                break;
            case 0:
                icon = <CloseCircleFilled style={{ color: "#d62728" }} />;
                break;
            default:
                icon = <QuestionCircleFilled style={{ color: "#ff9f4a" }} />
        }
        return icon;
    }

    getList(name, data, showSpin = false) {
        const total = this.props.seeds.length,
            checked = this.state.status.filter(d => d["Status"] !== undefined).length;
        let spin;
        if (checked !== total && showSpin) {
            spin = <Spin tip={"Checking..."} />
        }
        if (data.length > 0) {
            return (
                <div className="seed-papers">
                    <span className="label">Seed papers {name} ({data.length}/{total}) {spin}</span>
                    {data.sort((a, b) => a["Title"].localeCompare(b["Title"]))
                        .map(e => <a key={e["Title"].replace(" ", "-")} href={e["Url"]} target="_blank" rel="noreferrer">{this.getIcon(e["Title"])} {e["Title"]}</a>)}
                </div>
            );
        }
    }

    render() {
        return (
            <>
                {this.getList("excluded", this.state.status.filter(s => s["Status"] === 0))}
                {this.getList("to check", this.state.status.filter(s => s["Status"] === undefined), true)}
                {this.getList("included", this.state.status.filter(s => s["Status"] === 1))}
            </>
        );
    }
}

export default SeedPapers;
