// client/src/Abstract.jsx
import React from "react";
import './Abstract.css';
import parse from 'html-react-parser';

class Abstract extends React.Component {
    render() {
        const data = this.props.data,
            title = data["coredata"]["dc:title"],
            keyword = this.props.keyword["Keyword"].replace(/"/g, ""),
            regex = new RegExp(keyword, "i");

        let abstract;
        try {
            abstract = data["coredata"]["dc:description"].replace(regex, `<span className="highlight">${keyword}</span>`);
        } catch {
            abstract = "Abstract unavailable."
        }

        let keywords;
        if (data["authkeywords"]) {
            const keywordString = data["authkeywords"]["author-keyword"].map(k => k["$"]).join("; ")
                .replace(regex, `<span className="highlight">${keyword}</span>`);
            keywords = <p className="keywords"><span>Keywords: </span>{parse(keywordString)}</p>;
        }

        return (
            <div className="abstract">
                <p className="label">{title}</p>
                <p>{parse(abstract)}</p>
                {keywords}
            </div>
        );
    }
}

export default Abstract;

// src/lib/components/Abstract.svelte
<script>
	let { data, keyword } = $props();

	const title = $derived(data['coredata']['dc:title']);
	const cleanKeyword = $derived(keyword['Keyword'].replace(/"/g, ''));

	function highlight(text) {
		try {
			const regex = new RegExp(cleanKeyword, 'i');
			return text.replace(regex, (match) => `<span class="highlight">${match}</span>`);
		} catch {
			return text;
		}
	}

	const abstract = $derived.by(() => {
		const text = data['coredata']['dc:description'];
		return text ? highlight(text) : 'Abstract unavailable.';
	});

	const keywords = $derived.by(() => {
		const kws = data['authkeywords']?.['author-keyword'];
		if (!kws) return null;
		return highlight(kws.map((k) => k['$']).join('; '));
	});
</script>

<div class="abstract card p-4">
	<p class="label">{title}</p>
	<p>{@html abstract}</p>
	{#if keywords}
		<p class="keywords"><span>Keywords: </span>{@html keywords}</p>
	{/if}
</div>
