// client/src/QueryResult.jsx
import React from 'react';
import Abstract from './Abstract';
import BarChart from './BarChart';

class QueryResult extends React.Component {
    constructor(props) {
        super(props);
        this.handleBarClick = this.handleBarClick.bind(this);
    }

    handleBarClick(keyword, category) {
        this.props.onAbstractChange(keyword, category);
    }

    render() {
        let result;
        if ("search-results" in this.props.data) {
            result = <h2>{parseInt(this.props.data["search-results"]["opensearch:totalResults"]).toLocaleString()} hits</h2>;
        } else if ("service-error" in this.props.data || "error-response" in this.props.data) {
            result = "Scopus returned an error message. Check your API key and try connecting to the KU Leuven campus wifi or VPN.";
        }

        let impactChart;
        if (this.props.keywordImpacts.length > 0) {
            impactChart = <BarChart data={this.props.keywordImpacts}
                width="500"
                height="500"
                colour={this.props.colour}
                onBarClick={this.handleBarClick} />;
        }

        let abstracts;
        if (this.props.abstracts.length > 0) {
            abstracts = <div className="abstracts">
                <span className="label">Papers containing {this.props.activeKeyword["Keyword"]}</span>
                {this.props.abstracts.map(a => <Abstract data={a} keyword={this.props.activeKeyword} key={a["coredata"]["prism:doi"]} />)}
            </div>;
        }

        return (
            <>
                {result}
                {impactChart}
                {abstracts}
            </>
        )
    };
}

export default QueryResult;

// src/lib/components/QueryResult.svelte
<script>
	import Abstract from './Abstract.svelte';
	import BarChart from './BarChart.svelte';

	let { data, keywordImpacts, colour, abstracts, activeKeyword, onabstractchange } = $props();

	const hits = $derived(
		'search-results' in data ? parseInt(data['search-results']['opensearch:totalResults']) : null
	);
	const errored = $derived('service-error' in data || 'error-response' in data);

	function handleBarClick(keyword, category) {
		onabstractchange(keyword, category);
	}
</script>

{#if hits !== null}
	<h2>{hits.toLocaleString()} hits</h2>
{:else if errored}
	<p>
		Scopus returned an error message. Check your API key and try connecting to the KU Leuven
		campus wifi or VPN.
	</p>
{/if}

{#if keywordImpacts.length > 0}
	<BarChart data={keywordImpacts} width={500} colour={colour} onbarclick={handleBarClick} />
{/if}

{#if abstracts.length > 0}
	<div class="abstracts flex flex-col gap-2">
		<span class="label">Papers containing {activeKeyword['Keyword']}</span>
		{#each abstracts as a (a['coredata']['prism:doi'])}
			<Abstract data={a} keyword={activeKeyword} />
		{/each}
	</div>
{/if}
